import 'package:book_app_nav_2/model/author.dart';
import 'package:book_app_nav_2/model/book.dart';
import 'package:book_app_nav_2/model/publication.dart';

List<Author> authorList = [
  Author(id: 0, firstName: 'GS', lastName: 'Poudel'),
  Author(id: 1, firstName: 'William', lastName: 'Shakespeare'),
  Author(id: 2, firstName: 'Vladimir', lastName: 'Nabokov'),
  Author(id: 3, firstName: 'Laxmi', middleName: 'Prasad', lastName: 'Devkota'),
  Author(id: 4, firstName: 'Jane', lastName: 'Austen'),
  Author(id: 5, firstName: 'Paulo', lastName: 'Coelho'),
  Author(id: 6, firstName: 'F. Scott', lastName: 'Fitzgerald'),
  Author(id: 7, firstName: 'Og', lastName: 'Mandino'),
  Author(id: 8, firstName: 'Robin', lastName: 'Sharma'),
  Author(id: 9, firstName: 'Ernest', lastName: 'Hemingway'),
  Author(id: 10, firstName: 'Harper', lastName: 'Lee'),
];

final List<Book> books = [
  Book(
    'एक सर्को माया',
    'GS Poudel',
    'ek_sarko_maya',
    imageUrl: 'assets/images/ek_sarko_maya.jpg',
    authors: authorList[0],
    publication:
        Publication(name: 'Bulbul Publication', slug: 'bulbul_publication'),
    rating: 4.12,
    ratingCount: 178,
    publishedDate: '1 January 2019',
  ),
  Book(
    'Hamlet',
    'William Shakespeare',
    'hamlet',
    imageUrl: 'assets/images/hamlet.jpg',
    authors: authorList[1],
    publication: Publication(name: ''),
    publishedDate: '1603',
    rating: 4.03,
    ratingCount: 813625,
  ),
  Book(
    'Lolita',
    'Vladimir Nabokov',
    'lolita',
    imageUrl: 'assets/images/lolita.jpg',
    authors: authorList[2],
    publication: Publication(name: ''),
    rating: 3.8,
    ratingCount: 99,
    publishedDate: 'September 1955',
  ),
  Book(
    'मुनामदन',
    'Laxi Pd. Devkota',
    'muna_madan',
    imageUrl: 'assets/images/muna_madan.jpg',
    authors: authorList[3],
    publication:
        Publication(name: 'Manjari Publication', slug: 'manjari_publication'),
    rating: 4.32,
    ratingCount: 1531,
    publishedDate: '1936',
  ),
  Book(
    'Pride and Prejudice',
    'Jane Austen',
    'pride_and_prejudice',
    imageUrl: 'assets/images/pride_and_prejudice.jpg',
    authors: authorList[4],
    publication:
        Publication(name: 'CreateSpace Independent Publishing Platform'),
    rating: 4.27,
    ratingCount: 3489132,
    publishedDate: 'January 28, 1813',
  ),
  Book(
    'The Alchemist',
    'Paulo Coelho',
    'the_alchemist',
    imageUrl: 'assets/images/the_alchemist.jpg',
    authors: authorList[5],
    publication: Publication(name: 'HarperTorch (English translation)'),
    rating: 4.7,
    ratingCount: 2181,
    publishedDate: '1988',
  ),
  Book(
    'The Great Gatsby',
    'F. Scott Fitzgerald',
    'the_great_gatsby',
    imageUrl: 'assets/images/the_great_gatsby.jpg',
    authors: authorList[6],
    publication: Publication(name: 'T. Egerton, Whitehall'),
    rating: 3.93,
    ratingCount: 4318278,
    publishedDate: '1925',
  ),
  Book(
    'The Greatest Salesman In The World',
    'Og Mandino',
    'the_greatest_salesman_in_the_world',
    imageUrl: 'assets/images/the_greates_salesman_in_the_world.jpeg',
    authors: authorList[7],
    publication: Publication(name: 'Random House Publishing Group'),
    rating: 4.2,
    publishedDate: '1968',
  ),
  Book(
    'The Monk Who Sold His Ferrari',
    'Robin Sharma',
    'the_monk_who_sold_his_ferrari',
    imageUrl: 'assets/images/the_monk_who_sold_his_ferrarai.jpg',
    authors: authorList[8],
    publication: Publication(name: 'Harper Collins Publishers'),
    rating: 4.7,
    ratingCount: 425,
    publishedDate: '1996',
  ),
  Book(
    'The Old Man and the Sea',
    'Ernest Hemingway',
    'the_old_man_and_the_sea',
    imageUrl: 'assets/images/the_old_man_and_the_sea.jpg',
    authors: authorList[9],
    publication: Publication(name: 'Charles Scribner\'s Sons'),
    rating: 4.2,
    ratingCount: 369,
    publishedDate: 'September 1, 1952',
  ),
  Book(
    'To Kill a Mockingbird',
    'Harper Lee',
    'to_kill_a_mockingbird',
    imageUrl: 'assets/images/to_kill_a_moking_bird.jpg',
    authors: authorList[10],
    publication: Publication(name: 'J. B. Lippincott & Co.'),
    rating: 4.1,
    ratingCount: 1233,
    publishedDate: '1960',
  ),
];
